export const QUERY_KEYS = {
  //AUTH
  AUTH: "AUTH",

  //DEPARTMENT

  DEPARTMENT: "DEPARTMENT",
  DEPARTMENTS: "DEPARTMENTS",

  //EMPLOYEE

  EMPLOYEE: "EMPLOYEE",
  EMPLOYEES_SELECT: "EMPLOYEES_SELECT",

  EMPLOYEES: "EMPLOYEES",

  //ABSENCE

  ABSENCE: "ABSENCE",
  CHECK_CHECK_IN: "CHECK_CHECK_IN",
  CHECK_CHECK_OUT: "CHECK_CHECK_OUT",

  ABSENCES_OF_EMPLOYEE: "ABSENCES_OF_EMPLOYEE",

  ABSENCES: "ABSENCES",
};
