export const CONTEXT_TYPEs = {
  //AUTH
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",

  //IMAGE

  //UI

  REFRESH_UI: "REFRESH_UI",
  PROFILE_FORM: "PROFILE_FORM",
  EMPLOYEE_FORM: "EMPLOYEE_FORM",
  DEPARTMENT_FORM: "DEPARTMENT_FORM",

  //UTIL
  REFRESH_UTIL: "REFRESH_UTIL",
  OPERATION: "OPERATION",

  //OPERATION

  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  CHECK_IN: "CHECK_IN",
  CHECK_OUT: "CHECK_OUT",
};
